spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: dcqdy
    url: jdbc:mysql://localhost:3306/dialect?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.wpc.entity
